@echo off

set SRC=C:\msys64\mingw64\bin

copy "%SRC%\edit.dll" bin\
copy "%SRC%\freebl3.dll" bin\
copy "%SRC%\libasprintf-0.dll" bin\
copy "%SRC%\libatomic-1.dll" bin\
copy "%SRC%\libb2-1.dll" bin\
copy "%SRC%\libbrotlicommon.dll" bin\
copy "%SRC%\libbrotlidec.dll" bin\
copy "%SRC%\libbrotlienc.dll" bin\
copy "%SRC%\libbz2-1.dll" bin\
copy "%SRC%\libcairo-2.dll" bin\
copy "%SRC%\libcairo-gobject-2.dll" bin\
copy "%SRC%\libcairo-script-interpreter-2.dll" bin\
copy "%SRC%\libcares-2.dll" bin\
copy "%SRC%\libcharset-1.dll" bin\
copy "%SRC%\libcrypto-3-x64.dll" bin\
copy "%SRC%\libcurl-4.dll" bin\
copy "%SRC%\libdeflate.dll" bin\
copy "%SRC%\libexpat-1.dll" bin\
copy "%SRC%\libffi-8.dll" bin\
copy "%SRC%\libfontconfig-1.dll" bin\
copy "%SRC%\libformw6.dll" bin\
copy "%SRC%\libfreetype-6.dll" bin\
copy "%SRC%\libgcc_s_seh-1.dll" bin\
copy "%SRC%\libgif-7.dll" bin\
copy "%SRC%\libgio-2.0-0.dll" bin\
copy "%SRC%\libgirepository-2.0-0.dll" bin\
copy "%SRC%\libglib-2.0-0.dll" bin\
copy "%SRC%\libgmodule-2.0-0.dll" bin\
copy "%SRC%\libgmp-10.dll" bin\
copy "%SRC%\libgmpxx-4.dll" bin\
copy "%SRC%\libgnutls-30.dll" bin\
copy "%SRC%\libgnutls-openssl-27.dll" bin\
copy "%SRC%\libgnutlsxx-30.dll" bin\
copy "%SRC%\libgobject-2.0-0.dll" bin\
copy "%SRC%\libgomp-1.dll" bin\
copy "%SRC%\libgraphite2.dll" bin\
copy "%SRC%\libgthread-2.0-0.dll" bin\
copy "%SRC%\libharfbuzz-0.dll" bin\
copy "%SRC%\libharfbuzz-gobject-0.dll" bin\
copy "%SRC%\libharfbuzz-subset-0.dll" bin\
copy "%SRC%\libhistory8.dll" bin\
copy "%SRC%\libhogweed-6.dll" bin\
copy "%SRC%\libiconv-2.dll" bin\
copy "%SRC%\libidn2-0.dll" bin\
copy "%SRC%\libintl-8.dll" bin\
copy "%SRC%\libisl-23.dll" bin\
copy "%SRC%\libjbig-0.dll" bin\
copy "%SRC%\libjpeg-8.dll" bin\
copy "%SRC%\liblcms2-2.dll" bin\
copy "%SRC%\liblcms2_fast_float-2.dll" bin\
copy "%SRC%\libLerc.dll" bin\
copy "%SRC%\liblzma-5.dll" bin\
copy "%SRC%\liblzo2-2.dll" bin\
copy "%SRC%\libmenuw6.dll" bin\
copy "%SRC%\libmpc-3.dll" bin\
copy "%SRC%\libmpdec++-4.dll" bin\
copy "%SRC%\libmpdec-4.dll" bin\
copy "%SRC%\libmpfr-6.dll" bin\
copy "%SRC%\libncurses++w6.dll" bin\
copy "%SRC%\libncursesw6.dll" bin\
copy "%SRC%\libnettle-8.dll" bin\
copy "%SRC%\libnghttp2-14.dll" bin\
copy "%SRC%\libnghttp3-9.dll" bin\
copy "%SRC%\libngtcp2-16.dll" bin\
copy "%SRC%\libngtcp2_crypto_gnutls-8.dll" bin\
copy "%SRC%\libngtcp2_crypto_ossl-0.dll" bin\
copy "%SRC%\libnspr4.dll" bin\
copy "%SRC%\libopenjp2-7.dll" bin\
copy "%SRC%\libopenjpip-7.dll" bin\
copy "%SRC%\libp11-kit-0.dll" bin\
copy "%SRC%\libpanelw6.dll" bin\
copy "%SRC%\libpcre2-16-0.dll" bin\
copy "%SRC%\libpcre2-32-0.dll" bin\
copy "%SRC%\libpcre2-8-0.dll" bin\
copy "%SRC%\libpcre2-posix-3.dll" bin\
copy "%SRC%\libpixman-1-0.dll" bin\
copy "%SRC%\libplc4.dll" bin\
copy "%SRC%\libplds4.dll" bin\
copy "%SRC%\libpng16-16.dll" bin\
copy "%SRC%\libpoppler-156.dll" bin\
copy "%SRC%\libpoppler-cpp-3.dll" bin\
copy "%SRC%\libpoppler-glib-8.dll" bin\
copy "%SRC%\libpsl-5.dll" bin\
copy "%SRC%\libpython3.14.dll" bin\
copy "%SRC%\libpython3.dll" bin\
copy "%SRC%\libquadmath-0.dll" bin\
copy "%SRC%\libreadline8.dll" bin\
copy "%SRC%\libsharpyuv-0.dll" bin\
copy "%SRC%\libsqlite3-0.dll" bin\
copy "%SRC%\libssh2-1.dll" bin\
copy "%SRC%\libssl-3-x64.dll" bin\
copy "%SRC%\libstdc++-6.dll" bin\
copy "%SRC%\libsystre-0.dll" bin\
copy "%SRC%\libtasn1-6.dll" bin\
copy "%SRC%\libtermcap-0.dll" bin\
copy "%SRC%\libtiff-6.dll" bin\
copy "%SRC%\libtiffxx-6.dll" bin\
copy "%SRC%\libtre-5.dll" bin\
copy "%SRC%\libturbojpeg.dll" bin\
copy "%SRC%\libunistring-5.dll" bin\
copy "%SRC%\libwebp-7.dll" bin\
copy "%SRC%\libwebpdecoder-3.dll" bin\
copy "%SRC%\libwebpdemux-2.dll" bin\
copy "%SRC%\libwebpmux-3.dll" bin\
copy "%SRC%\libwinpthread-1.dll" bin\
copy "%SRC%\libzstd.dll" bin\
copy "%SRC%\nss3.dll" bin\
copy "%SRC%\nssckbi.dll" bin\
copy "%SRC%\nssutil3.dll" bin\
copy "%SRC%\smime3.dll" bin\
copy "%SRC%\softokn3.dll" bin\
copy "%SRC%\ssl3.dll" bin\
copy "%SRC%\tcl86.dll" bin\
copy "%SRC%\tk86.dll" bin\
copy "%SRC%\zlib1.dll" bin\
pause